package net.projecteuler.dustinbarnes;

import org.junit.Test;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.junit.Assert.assertThat;


/**
 * http://projecteuler.net/index.php?section=problems&id=29
 *
 * How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
 */
public class Problem29Test
{
    private Problem29 problem29 = new Problem29();

    @Test
    public void testNumberOfDistinctTermsProblem() throws Exception
    {
        assertThat(problem29.numberOfDistinctTerms(2, 100), equalTo(9183));
    }

    @Test
    public void testNumberOfDistinctTermsGiven() throws Exception
    {
        assertThat(problem29.numberOfDistinctTerms(2, 5), equalTo(15));
    }
}
