package net.projecteuler.dustinbarnes;

import java.util.Set;
import java.util.TreeSet;


/**
 * http://projecteuler.net/index.php?section=problems&id=29
 *
 * How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
 */
public class Problem29
{
    public int numberOfDistinctTerms(int lowerBound, int upperBound)
    {
        Set<Double> terms = new TreeSet<Double>();

        for ( double a = lowerBound; a <= upperBound; a++ )
        {
            for ( double b = lowerBound; b <= upperBound; b++ )
            {
                terms.add(Math.pow(a, b));
            }
        }

        return terms.size();
    }
}
